# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShibaInu_baseDB.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 244, 210);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 20, 721, 511))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Delete = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Delete.setStyleSheet("font: italic 20pt \"Monotype Corsiva\";")
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.gridLayout.addWidget(self.pushButton_Delete, 1, 3, 1, 1)
        self.pushButton_Insert = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Insert.setStyleSheet("font: italic 20pt \"Monotype Corsiva\";")
        self.pushButton_Insert.setObjectName("pushButton_Insert")
        self.gridLayout.addWidget(self.pushButton_Insert, 1, 1, 1, 1)
        self.pushButton_Select = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Select.setStyleSheet("font: italic 20pt \"Monotype Corsiva\";")
        self.pushButton_Select.setObjectName("pushButton_Select")
        self.gridLayout.addWidget(self.pushButton_Select, 1, 0, 1, 1)
        self.pushButton_Update = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Update.setStyleSheet("font: italic 20pt \"Monotype Corsiva\";")
        self.pushButton_Update.setObjectName("pushButton_Update")
        self.gridLayout.addWidget(self.pushButton_Update, 1, 2, 1, 1)
        self.pushButton_Exit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Exit.setStyleSheet("font: italic 20pt \"Monotype Corsiva\";")
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.gridLayout.addWidget(self.pushButton_Exit, 1, 4, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setStyleSheet("background-color: rgb(222, 213, 183);\n"
"font: italic 16pt \"Monotype Corsiva\";\n"
"gridline-color: rgb(150, 143, 124);\n"
"border-color: rgb(163, 156, 134);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_Exit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "База Данных \"Сиба Ину\""))
        self.pushButton_Delete.setText(_translate("MainWindow", "DELETE"))
        self.pushButton_Insert.setText(_translate("MainWindow", "INSERT"))
        self.pushButton_Select.setText(_translate("MainWindow", "SELECT"))
        self.pushButton_Update.setText(_translate("MainWindow", "UPDATE"))
        self.pushButton_Exit.setText(_translate("MainWindow", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
