# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShibaInu_baseDB.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QApplication, QDialog, QInputDialog, QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 244, 210);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 20, 721, 511))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Delete = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Delete.setStyleSheet("font: italic 20pt \"Monotype Corsiva\";")
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.gridLayout.addWidget(self.pushButton_Delete, 1, 3, 1, 1)
        self.pushButton_Update = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Update.setStyleSheet("font: italic 20pt \"Monotype Corsiva\";")
        self.pushButton_Update.setObjectName("pushButton_Update")
        self.gridLayout.addWidget(self.pushButton_Update, 1, 2, 1, 1)
        self.pushButton_Exit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Exit.setStyleSheet("font: italic 20pt \"Monotype Corsiva\";")
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.gridLayout.addWidget(self.pushButton_Exit, 1, 4, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setStyleSheet("background-color: rgb(222, 213, 183);\n"
"font: italic 16pt \"Monotype Corsiva\";\n"
"gridline-color: rgb(150, 143, 124);\n"
"border-color: rgb(163, 156, 134);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setSelectionMode(QtWidgets.QTableWidget.SingleSelection)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 5)
        self.pushButton_Insert = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Insert.setStyleSheet("font: italic 20pt \"Monotype Corsiva\";")
        self.pushButton_Insert.setObjectName("pushButton_Insert")
        self.gridLayout.addWidget(self.pushButton_Insert, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.load()

        self.retranslateUi(MainWindow)
        self.pushButton_Exit.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_Insert.clicked.connect(self.insert)
        self.pushButton_Delete.clicked.connect(self.delete)
        self.pushButton_Update.clicked.connect(self.Update)
        self.tableWidget.itemChanged.connect(self.on_cell_edited)
        self.tableWidget.itemClicked.connect(self.item)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def Update(self):
        self.tableWidget.blockSignals(True)
        self.load()
        self.tableWidget.blockSignals(False)
    def item(self, item):
        global old_value
        old_value = item.text()
    def on_cell_edited(self, item):
        connection = sqlite3.connect('Shiba_Inu.db')
        cursor = connection.cursor()
        row = item.row()
        value = item.text()
        column = item.column()
        if column == 4:
           QMessageBox.critical(None, "Error", "НЕЛЬЗЯ РЕДАКТИРОВАТЬ ЭТО ПОЛЕ. ПОЖАЛУЙСТА ОБНОВИ ТАБЛИЦУ ЧЕРЕЗ КНОПКУ")
           return
        IDI = self.tableWidget.item(row, 0).text()
        column_names = ['id', 'username', 'email', 'age']
        column = column_names[column]
        try:
            cursor.execute(f"UPDATE Dogs SET {column} = ? WHERE id = ?", (value, int(IDI)))
            connection.commit()
            connection.close()
            QMessageBox.information(None, "Error", "Вы ввели подходящее значение")
        except:
             QMessageBox.critical(None, "Error", "Вы ввели неподходящее значение. Обнови таблицу")
             return
    def load(self):
        connection = sqlite3.connect('Shiba_Inu.db')
        cursor = connection.cursor()

        cursor.execute('SELECT * FROM Dogs')
        dogs = cursor.fetchall()
        self.tableWidget.setRowCount(len(dogs))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setHorizontalHeaderLabels(['ID', 'Имя', 'Почта', 'Возраст', 'Когда создалась запись']) 

        for i, row in enumerate(dogs):
            for j, value in enumerate(row):
                self.tableWidget.setItem(i,j, QtWidgets.QTableWidgetItem(str(value)))

        cursor.close()
        return
    def insert(self):
        connection = sqlite3.connect('Shiba_Inu.db')
        cursor = connection.cursor()
        text, ok = QInputDialog.getText(None, "Добавление записи", "Введите через запятую и пробел строку записи (код собаки и время создания не писать не вводить не вводить):")

        if ok:
            text = text.split(', ')
            if len(text) != 4:
                QMessageBox.critical(None, "Error", "Пожалуйста, введите только следующие поля : id, username, email, age")
                return
            else:
                try:
                    cursor.execute('INSERT INTO Dogs (id, username, email, age) VALUES (?, ?, ?, ?)', (text[0], text[1], text[2], text[3]))
                except:
                   QMessageBox.critical(None, "Error", "Запись с таким кодом уже есть")
                connection.commit()
                connection.close()
                self.load()
        else:
            pass
    def delete(self):
        connection = sqlite3.connect('Shiba_Inu.db')
        cursor = connection.cursor()
        text, ok = QInputDialog.getText(None, "Удаление записи", "Введите только код собаки:")

        if ok:
            text = text.split(', ')
            if len(text) != 1:
                QMessageBox.critical(None, "Error", "Пожалуйста, введите только следующее поле : id")
                return
            else:
                try:
                    cursor.execute('DELETE FROM Dogs WHERE id = ? ', (text[0],))
                except:
                   QMessageBox.critical(None, "Error", "Запись с таким кодом уже удалена")
                connection.commit()
                connection.close()
                self.load()
        else:
            pass

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "База Данных \"Сиба Ину\""))
        self.pushButton_Delete.setText(_translate("MainWindow", "DELETE"))
        self.pushButton_Update.setText(_translate("MainWindow", "UPDATE"))
        self.pushButton_Exit.setText(_translate("MainWindow", "EXIT"))
        self.pushButton_Insert.setText(_translate("MainWindow", "INSERT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
