# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DiaZak.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Zak(object):
    def setupUi(self, Dialog_Zak):
        Dialog_Zak.setObjectName("Dialog_Zak")
        Dialog_Zak.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_Zak)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog_Zak)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 30, 321, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 4, 1, 1, 1)

        self.retranslateUi(Dialog_Zak)
        self.buttonBox.accepted.connect(Dialog_Zak.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_Zak.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_Zak)

    def retranslateUi(self, Dialog_Zak):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Zak.setWindowTitle(_translate("Dialog_Zak", "Добавление/Редактирование заказов"))
        self.label.setText(_translate("Dialog_Zak", "Код заказа"))
        self.label_2.setText(_translate("Dialog_Zak", "Код путевки"))
        self.label_5.setText(_translate("Dialog_Zak", "Дата прибытия"))
        self.label_4.setText(_translate("Dialog_Zak", "Количество людей"))
        self.label_3.setText(_translate("Dialog_Zak", "Код туриста"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Zak = QtWidgets.QDialog()
    ui = Ui_Dialog_Zak()
    ui.setupUi(Dialog_Zak)
    Dialog_Zak.show()
    sys.exit(app.exec_())
